[package]
name = "keylogger_vfinal_client"
version = "0.1.0"
edition = "2021"

[dependencies]
#chrono = "0.4.30"
#clap = { version = "4", features = ["derive"] }
device_query = "1.1.3"

[profile.release]
opt-level = "s"
strip = true
lto = true
panic = "abort"
