[package]
name = "keylogger_vfinal_server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }

[profile.release]
opt-level = "s"
strip = true
lto = true
panic = "abort"
